"""Initial migration

Revision ID: 9ba4edfe217c
Revises: 
Create Date: 2025-02-14 13:00:34.903721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ba4edfe217c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temperature_data')
    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.alter_column('temperature_in_tank',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('temperature_in_house',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('humidity_in_house',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_sensor_data_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensor_data_timestamp'))
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('humidity_in_house',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('temperature_in_house',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('temperature_in_tank',
               existing_type=sa.FLOAT(),
               nullable=False)

    op.create_table('temperature_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('month', sa.INTEGER(), nullable=False),
    sa.Column('day', sa.INTEGER(), nullable=False),
    sa.Column('temperature', sa.FLOAT(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
